// ficheiro: js/languages-zmaj.js
// ATENÇÃO: Mantido no escopo global intencionalmente (Sem Export/Import) para não quebrar integrações do GSAP.

const translationsZmaj = {
    en: {
        doc_title: "Zmaj | The Future of Mobility",
        doc_desc: "Zmaj is innovating the future of urban mobility in Ljubljana. Silent, zero-emission e-bikes.",
        nav_vision: "Vision", nav_app: "App", nav_plans: "Plans", nav_contacts: "Contacts", nav_download: "Download",
        hero_1: "Engineering the future of <br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">urban mobility.</span>",
        hero_2: "Designed in Ljubljana.<br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">Built for the world.</span>",
        hero_3: "Zero emissions.<br /><span class=\"text-transparent bg-clip-text bg-gradient-to-r from-brand-aura to-white drop-shadow-lg\">Pure performance.</span>",
        man_tag: "Zmaj Manifesto", man_title: "LJUBLJANA'S SOUL",
        man_c1_t: "The Heritage", man_c1_tag: "Plečnik’s Vision", man_c1_d: "Since 2007, Ljubljana’s historical center has been a car-free ecological zone of 12 hectares. Zmaj is the technological infrastructure designed to respect Jože Plečnik’s human-scale architecture, providing silent, zero-emission mobility for the soul of the city.",
        man_c2_t: "The Urban Pulse", man_c2_tag: "Digital Rhythm", man_c2_d: "A smart, invisible skeleton powers the city. The Zmaj network breathes life into urban commutes. Scan effortlessly, ride silently, and dock seamlessly at illuminated Zmaj Spots spread across town. Digital convenience meets physical freedom.", man_c2_btn_text: "Download Zmaj App",
        man_c3_t: "The Green Symbiosis", man_c3_tag: "Social Impact", man_c3_d: "As the first EU capital to commit to a Zero Waste vision, Ljubljana relies on Zmaj to bridge the gap between urban growth and environmental preservation. By neutralizing carbon footprints and restoring the city’s natural silence, we ensure that the only pulse felt along the Ljubljanica banks is the rhythm of life itself.",
        hub_tl: "Digital Ecosystem", hub_c1_t: "Connected Ecosystem", hub_c1_d: "Smart dashboard with ride estimates and daily usage statistics in the city.",
        hub_c2_t: "Zero Impact", hub_c2_d: "Track your reduced carbon footprint in real-time. Move while cleaning the air.",
        hub_c3_t: "Active Security", hub_c3_d: "Perimeter monitoring via Bluetooth and immediate anti-theft locking system.",
        hub_tr: "Plans & Performance", hub_p1_tag: "Starter", hub_p1_t: "Daily Pass", hub_p1_d: "Perfect for travelers and occasional riders. 24-hour e-bike access.", hub_p1_pr: "€5<span class=\"text-xs font-sans text-brand-muted font-normal\">/day</span>", hub_p_btn_text: "Select Plan",
        hub_p2_badge: "POPULAR", hub_p2_tag: "Zmaj Pro", hub_p2_t: "Annual Plan", hub_p2_d: "Unlimited rides, priority support, and theft coverage.", hub_p2_f1: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Unlimited Rides", hub_p2_f2: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Theft Coverage", hub_p2_pr: "€29<span class=\"text-xs font-sans text-brand-muted font-normal\">/month</span>",
        hub_p3_tag: "Fleet", hub_p3_t: "Business", hub_p3_d: "Custom solutions for companies and hotels.", hub_p3_pr: "Custom", hub_p3_btn_text: "Contact Us",
        hub_i1: "Engineering the future of <br /><span class='text-[#4B5EC2]'>connected mobility.</span>", hub_i2: "Total control <br /><span class='text-[#4B5EC2]'>at your fingertips.</span>",
        imp_lbl: "Energy Recovered", imp_kin_t: "Kinetic energy regenerated", imp_kin_d: "Power automatically recovered through our smart regenerative braking system.",
        imp_f1: "Zmaj Active Fleet", imp_f2: "Connected Hubs", imp_f3: "Urban Rail Offset",
        imp_c_t: "Cloud latency", imp_c_d: "Real-time bike-to-app telemetry",
        imp_ai_t: "Predictive AI Routing", imp_ai_d: "Constantly analyzing traffic, topography, and battery to map your perfect trajectory.",
        imp_m1: "Live Traffic Mapping", imp_m1_tag: "Active", imp_m2: "Hyper-local Weather", imp_m3: "Zmaj AI Engine Connect",
        imp_mwh: "MWh", imp_ms: "ms",
        dl_t1: "Available for <br />download now", dl_app: "Download on the", dl_app_store: "App Store", dl_play: "Get it on", dl_google_play: "Google Play", dl_t2: "Scan to ride", dl_t3: "Join the future of <br />urban mobility", dl_btn_text: "Get Early Access",
        ft_eco: "Ecosystem", ft_l1: "The E-Bike", ft_l2: "App Hub", ft_l3: "Urban Network",
        ft_comp: "Company", ft_l4: "Our Journey", ft_l5: "Ljubljana Base", ft_l6: "Press Kit",
        ft_upd: "Updates", ft_mail: "EMAIL ADDRESS", ft_sign: "SIGN UP", ft_quote: "\"Engineering the future of urban freedom.\"", ft_rights: "© 2026 ZMAJ MOBILITY"
    },
    pt: {
        doc_title: "Zmaj | O Futuro da Mobilidade",
        doc_desc: "A Zmaj está a inovar o futuro da mobilidade urbana em Ljubljana. E-bikes silenciosas e de zero emissões.",
        nav_vision: "Visão", nav_app: "App", nav_plans: "Planos", nav_contacts: "Contatos", nav_download: "Baixar",
        hero_1: "Desenhando o futuro da <br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">mobilidade urbana.</span>",
        hero_2: "Criada em Ljubljana.<br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">Feita para o mundo.</span>",
        hero_3: "Zero emissões.<br /><span class=\"text-transparent bg-clip-text bg-gradient-to-r from-brand-aura to-white drop-shadow-lg\">Performance pura.</span>",
        man_tag: "Manifesto Zmaj", man_title: "A ALMA DE LJUBLJANA",
        man_c1_t: "A Herança", man_c1_tag: "A Visão de Plečnik", man_c1_d: "Desde 2007, o centro histórico de Ljubljana é uma zona ecológica sem carros. A Zmaj é a infraestrutura tecnológica desenhada para respeitar a arquitetura à escala humana de Jože Plečnik.",
        man_c2_t: "O Pulso Urbano", man_c2_tag: "Ritmo Digital", man_c2_d: "Um esqueleto inteligente e invisível alimenta a cidade. Digitalize sem esforço, conduza em silêncio e estacione nos Zmaj Spots. A conveniência digital encontra a liberdade física.",
        man_c2_btn_text: "Baixar App Zmaj",
        man_c3_t: "A Simbiose Verde", man_c3_tag: "Impacto Social", man_c3_d: "Sendo a primeira capital da UE a comprometer-se com uma visão Zero Resíduos, Ljubljana conta com a Zmaj para unir o crescimento urbano à preservação ambiental neutralizando a pegada de carbono.",
        hub_tl: "Ecossistema Digital", hub_c1_t: "Ecossistema Conectado", hub_c1_d: "Dashboard inteligente com estimativas de viagem e estatísticas diárias na cidade.",
        hub_c2_t: "Impacto Zero", hub_c2_d: "Monitorize a sua pegada de carbono reduzida em tempo real. Mova-se enquanto limpa o ar.",
        hub_c3_t: "Segurança Ativa", hub_c3_d: "Monitorização de perímetro via Bluetooth e sistema de bloqueio antirroubo imediato.",
        hub_tr: "Planos & Performance", hub_p1_tag: "Inicial", hub_p1_t: "Passe Diário", hub_p1_d: "Perfeito para viajantes e utilizadores ocasionais. 24 horas de acesso e-bike.", hub_p1_pr: "€5<span class=\"text-xs font-sans text-brand-muted font-normal\">/dia</span>",
        hub_p_btn_text: "Selecionar Plano",
        hub_p2_badge: "POPULAR", hub_p2_tag: "Zmaj Pro", hub_p2_t: "Plano Anual", hub_p2_d: "Viagens ilimitadas, suporte prioritário e cobertura contra roubo.", hub_p2_f1: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Viagens Ilimitadas", hub_p2_f2: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Cobertura contra Roubo", hub_p2_pr: "€29<span class=\"text-xs font-sans text-brand-muted font-normal\">/mês</span>",
        hub_p3_tag: "Frotas", hub_p3_t: "Empresarial", hub_p3_d: "Soluções personalizadas para empresas e hotéis.", hub_p3_pr: "Personalizado", hub_p3_btn_text: "Contacte-nos",
        hub_i1: "Desenhando o futuro da <br /><span class='text-[#4B5EC2]'>mobilidade conectada.</span>", hub_i2: "Controle total <br /><span class='text-[#4B5EC2]'>na ponta dos dedos.</span>",
        imp_lbl: "Energia Recuperada", imp_kin_t: "Energia cinética regenerada", imp_kin_d: "Energia recuperada automaticamente através do nosso sistema inteligente de travagem regenerativa.",
        imp_f1: "Frota Ativa Zmaj", imp_f2: "Hubs Conectados", imp_f3: "Compensação Ferroviária",
        imp_c_t: "Latência da Cloud", imp_c_d: "Telemetria bicicleta-app em tempo real",
        imp_ai_t: "Rotas de IA Preditiva", imp_ai_d: "Análise constante de trânsito, topografia e bateria para mapear a trajetória perfeita.",
        imp_m1: "Mapeamento de Trânsito ao Vivo", imp_m1_tag: "Ativo", imp_m2: "Meteorologia Hiper-local", imp_m3: "Conexão Motor IA Zmaj",
        imp_mwh: "MWh", imp_ms: "ms",
        dl_t1: "Disponível para <br />download agora", dl_app: "Baixar na", dl_app_store: "App Store", dl_play: "Disponível no", dl_google_play: "Google Play", dl_t2: "Digitalize para baixar", dl_t3: "Junte-se ao futuro da <br />mobilidade urbana",
        dl_btn_text: "Baixar agora",
        ft_eco: "Ecossistema", ft_l1: "A E-Bike", ft_l2: "App Hub", ft_l3: "Rede Urbana",
        ft_comp: "Empresa", ft_l4: "A Nossa Jornada", ft_l5: "Base em Ljubljana", ft_l6: "Kit de Imprensa",
        ft_upd: "Atualizações", ft_mail: "ENDEREÇO DE EMAIL", ft_sign: "SUBSCREVER", ft_quote: "\"Desenhando o futuro da liberdade urbana.\"", ft_rights: "© 2026 ZMAJ MOBILITY"
    },
    es: {
        doc_title: "Zmaj | El Futuro de la Movilidad",
        doc_desc: "Zmaj está innovando el futuro de la movilidad urbana en Liubliana. Bicicletas eléctricas silenciosas y de cero emisiones.",
        nav_vision: "Visión", nav_app: "App", nav_plans: "Planes", nav_contacts: "Contactos", nav_download: "Descargar",
        hero_1: "Diseñando el futuro de la <br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">movilidad urbana.</span>",
        hero_2: "Diseñada en Liubliana.<br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">Creada para el mundo.</span>",
        hero_3: "Cero emisiones.<br /><span class=\"text-transparent bg-clip-text bg-gradient-to-r from-brand-aura to-white drop-shadow-lg\">Rendimiento puro.</span>",
        man_tag: "Manifiesto Zmaj", man_title: "EL ALMA DE LIUBLIANA",
        man_c1_t: "El Patrimonio", man_c1_tag: "La Visión de Plečnik", man_c1_d: "Desde 2007, el centro histórico de Liubliana es una zona ecológica sin coches. Zmaj es la infraestructura diseñada para respetar la arquitectura de Jože Plečnik, proporcionando movilidad silenciosa.",
        man_c2_t: "El Pulso Urbano", man_c2_tag: "Ritmo Digital", man_c2_d: "Un esqueleto inteligente e invisible impulsa la ciudad. La red Zmaj da vida a los desplazamientos. Escanea sin esfuerzo, conduce en silencio y aparca en los Zmaj Spots.", man_c2_btn_text: "Descargar App Zmaj",
        man_c3_t: "La Simbiosis Verde", man_c3_tag: "Impacto Social", man_c3_d: "Como la primera capital de la UE en comprometerse con Cero Residuos, Liubliana confía en Zmaj para unir crecimiento urbano y preservación ambiental neutralizando la huella de carbono.",
        hub_tl: "Ecosistema Digital", hub_c1_t: "Ecosistema Conectado", hub_c1_d: "Panel inteligente con estimaciones de viaje y estadísticas diarias.",
        hub_c2_t: "Impacto Cero", hub_c2_d: "Rastrea tu huella de carbono reducida en tiempo real. Muévete mientras limpias el aire.",
        hub_c3_t: "Seguridad Activa", hub_c3_d: "Monitorización por Bluetooth y sistema de bloqueo antirrobo.",
        hub_tr: "Planes y Rendimiento", hub_p1_tag: "Inicial", hub_p1_t: "Pase Diario", hub_p1_d: "Perfecto para viajeros ocasionales. 24 horas de acceso a la e-bike.", hub_p1_pr: "€5<span class=\"text-xs font-sans text-brand-muted font-normal\">/día</span>", hub_p_btn_text: "Seleccionar Plan",
        hub_p2_badge: "POPULAR", hub_p2_tag: "Zmaj Pro", hub_p2_t: "Plan Anual", hub_p2_d: "Viajes ilimitados, soporte prioritario y cobertura contra robos.", hub_p2_f1: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Viajes Ilimitados", hub_p2_f2: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Cobertura contra Robos", hub_p2_pr: "€29<span class=\"text-xs font-sans text-brand-muted font-normal\">/mes</span>",
        hub_p3_tag: "Flota", hub_p3_t: "Negocios", hub_p3_d: "Soluciones personalizadas para empresas y hoteles.", hub_p3_pr: "Personalizado", hub_p3_btn_text: "Contáctenos",
        hub_i1: "Diseñando el futuro de la <br /><span class='text-[#4B5EC2]'>movilidad conectada.</span>", hub_i2: "Control total <br /><span class='text-[#4B5EC2]'>a tu alcance.</span>",
        imp_lbl: "Energía Recuperada", imp_kin_t: "Energía cinética regenerada", imp_kin_d: "Energía recuperada automáticamente mediante nuestro frenado regenerativo.",
        imp_f1: "Flota Activa Zmaj", imp_f2: "Hubs Conectados", imp_f3: "Compensación Ferroviaria",
        imp_c_t: "Latencia en la Nube", imp_c_d: "Telemetría bicicleta-app en tiempo real",
        imp_ai_t: "Rutas de IA Predictiva", imp_ai_d: "Análisis constante de tráfico, topografía y batería para tu trayectoria perfecta.",
        imp_m1: "Mapeo de Tráfico en Vivo", imp_m1_tag: "Activo", imp_m2: "Clima Hiperlocal", imp_m3: "Conexión Motor IA Zmaj",
        imp_mwh: "MWh", imp_ms: "ms",
        dl_t1: "Disponible para <br />descargar ahora", dl_app: "Consíguelo en el", dl_app_store: "App Store", dl_play: "Disponible en", dl_google_play: "Google Play", dl_t2: "Escanea para viajar", dl_t3: "Únete al futuro de la <br />movilidad urbana", dl_btn_text: "Acceso Anticipado",
        ft_eco: "Ecosistema", ft_l1: "La E-Bike", ft_l2: "App Hub", ft_l3: "Red Urbana",
        ft_comp: "Compañía", ft_l4: "Nuestro Viaje", ft_l5: "Base en Liubliana", ft_l6: "Kit de Prensa",
        ft_upd: "Actualizaciones", ft_mail: "CORREO ELECTRÓNICO", ft_sign: "SUSCRIBIRSE", ft_quote: "\"Diseñando el futuro de la libertad urbana.\"", ft_rights: "© 2026 ZMAJ MOBILITY"
    },
    sl: {
        doc_title: "Zmaj | Prihodnost mobilnosti",
        doc_desc: "Zmaj ustvarja prihodnost mestne mobilnosti v Ljubljani. Tiha e-kolesa brez izpustov.",
        nav_vision: "Vizija", nav_app: "Aplikacija", nav_plans: "Paketi", nav_contacts: "Stik", nav_download: "Prenesi",
        
        hero_1: "Snovanje prihodnosti <br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">mestne mobilnosti.</span>",
        hero_2: "Zasnovano v Ljubljani.<br /><span class=\"text-[#4B5EC2] mix-blend-color-burn\">Ustvarjeno za svet.</span>",
        hero_3: "Brez izpustov.<br /><span class=\"text-transparent bg-clip-text bg-gradient-to-r from-brand-aura to-white drop-shadow-lg\">Vrhunska zmogljivost.</span>",
        
        man_tag: "Manifest Zmaj", man_title: "DUŠA LJUBLJANE",
        man_c1_t: "Dediščina", man_c1_tag: "Plečnikova vizija", 
        man_c1_d: "Od leta 2007 je staro mestno jedro Ljubljane ekološka cona na 12 hektarih, zaprta za motorni promet. Zmaj je tehnološka infrastruktura, zasnovana s spoštovanjem do Plečnikove arhitekture po meri človeka, ki mestu zagotavlja tiho mobilnost brez izpustov.",
        man_c2_t: "Urbani utrip", man_c2_tag: "Digitalni ritem", 
        man_c2_d: "Mesto poganja pametno, nevidno okostje. Mreža Zmaj vdihne življenje v vsakodnevne poti. Skenirajte brez napora, vozite v tišini in parkirajte na osvetljenih točkah Zmaj. Digitalno udobje se sreča s fizično svobodo.",
        man_c2_btn_text: "Prenesi aplikacijo Zmaj",
        man_c3_t: "Zelena simbioza", man_c3_tag: "Družbeni vpliv", 
        man_c3_d: "Kot prva evropska prestolnica, zavezana viziji Zero Waste (nič odpadkov), Ljubljana z Zmajem združuje urbani razvoj z varovanjem okolja in nevtralizacijo ogljičnega odtisa.",
        
        hub_tl: "Digitalni ekosistem", hub_c1_t: "Popolna povezljivost", hub_c1_d: "Pametna nadzorna plošča z ocenami časa vožnje in dnevnimi statistikami uporabe.",
        hub_c2_t: "Brez vpliva na okolje", hub_c2_d: "Spremljajte zmanjšanje svojega ogljičnega odtisa v realnem času. Premikajte se in hkrati ohranjajte zrak čist.",
        hub_c3_t: "Aktivna varnost", hub_c3_d: "Nadzor okolice prek Bluetootha in takojšen sistem zaklepanja proti kraji.",
        
        hub_tr: "Paketi in zmogljivost", hub_p1_tag: "Začetni", hub_p1_t: "Dnevna vozovnica", 
        hub_p1_d: "Popolna izbira za obiskovalce in občasne uporabnike. 24-urni dostop do e-kolesa.", 
        hub_p1_pr: "5 €<span class=\"text-xs font-sans text-brand-muted font-normal\">/dan</span>",
        hub_p_btn_text: "Izberi paket",
        
        hub_p2_badge: "PRILJUBLJENO", hub_p2_tag: "Zmaj Pro", hub_p2_t: "Letni paket", 
        hub_p2_d: "Neomejeno število voženj, prioritetna podpora in zavarovanje proti kraji.", 
        hub_p2_f1: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Neomejene vožnje", 
        hub_p2_f2: "<span class=\"iconify text-[#4B5EC2]\" data-icon=\"solar:check-circle-bold\"></span> Zavarovanje proti kraji", 
        hub_p2_pr: "29 €<span class=\"text-xs font-sans text-brand-muted font-normal\">/mesec</span>",
        
        hub_p3_tag: "Flote", hub_p3_t: "Za podjetja", hub_p3_d: "Prilagojene rešitve za podjetja in hotele.", 
        hub_p3_pr: "Po dogovoru", hub_p3_btn_text: "Stopite v stik",
        
        hub_i1: "Snovanje prihodnosti <br /><span class='text-[#4B5EC2]'>povezane mobilnosti.</span>", 
        hub_i2: "Popoln nadzor <br /><span class='text-[#4B5EC2]'>na dlani.</span>",
        
        imp_lbl: "Pridobljena energija", imp_kin_t: "Regenerirana kinetična energija", 
        imp_kin_d: "Energija, ki se samodejno povrne prek našega pametnega sistema regenerativnega zaviranja.",
        imp_f1: "Aktivna flota Zmaj", imp_f2: "Povezana vozlišča", imp_f3: "Železniška kompenzacija",
        imp_c_t: "Odzivnost oblaka", imp_c_d: "Telemetrija v realnem času",
        imp_ai_t: "Predvidljivo usmerjanje (UI)", imp_ai_d: "Nenehna analiza prometa, terena in stanja baterije za iskanje popolne poti.",
        imp_m1: "Promet v živo", imp_m1_tag: "Aktivno", imp_m2: "Lokalno vreme", imp_m3: "Povezava Zmaj AI",
        imp_mwh: "MWh", imp_ms: "ms",
        
        dl_t1: "Zdaj na voljo <br />za prenos", dl_app: "Prenesi v", dl_app_store: "App Store", dl_play: "Na voljo v", dl_google_play: "Google Play", 
        dl_t2: "Skeniraj in pelji", dl_t3: "Pridruži se prihodnosti <br />mestne mobilnosti",
        dl_btn_text: "Zgodnji dostop",
        
        ft_eco: "Ekosistem", ft_l1: "E-kolo", ft_l2: "Aplikacija", ft_l3: "Mestno omrežje",
        ft_comp: "Podjetje", ft_l4: "Naša pot", ft_l5: "Baza Ljubljana", ft_l6: "Medijsko središče",
        ft_upd: "Novice", ft_mail: "E-POŠTNI NASLOV", ft_sign: "PRIJAVA", 
        ft_quote: "\"Snovanje prihodnosti urbane svobode.\"", ft_rights: "© 2026 ZMAJ MOBILITY"
    }
};
